version: '3.8'

services:
  web:
    build: .
    container_name: chat_app_web
    ports:
      - "8080:80"
    networks:
      - chat-app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: chat_app_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: chatapp
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - chat-app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: chat_app_phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    networks:
      - chat-app-network

volumes:
  db_data:

networks:
  chat-app-network:
    driver: bridge
